- name: variables to print 
  hosts: web
  tasks:
   - name: print the information
     ansible.builtin.debug:
      msg: "hi, i am learning {{COURSE}}, durtaion is: {{DURATION}}, trainer: {{TRAINER}}"